### PR TITLE
Add github actions to automatically build on commit

### PR DESCRIPTION
**Pull request by DragonEggBedrockBreaking**
Self explanatory; means that people don't have to build it themselves, if they don't know how to. Set to JDK 8 so that most people can use the builds. Did it only on commit not on pull request, so as not to confuse anyone. Didn't do this on tic-tacs because you already send builds to your jenkins.

### CODE REVIEW

**Comment by DragonEggBedrockBreaking** [comment]
temporarily closing for maintenance (don't ask)

**Comment by DragonEggBedrockBreaking** [comment]
re-opened; maintenance completed

**Comment by DragonEggBedrockBreaking** [comment]
i did an upsi again but i fixed it now

**Review by Gegy — APPROVED** [review]
Thanks!

**Pull request merged**
